networks:
  network:

volumes:
  opdata:

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.enterprise
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: postgresql://${DB_USER:-openproject}:${DB_PASSWORD:-openproject}@${DB_HOST:-192.168.3.78}:${DB_PORT:-5432}/${DB_NAME:-openproject}
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_RAILS__CACHE__STORE: memcache
      OPENPROJECT_WEB_WORKERS: ${WEB_WORKERS:-2}
      OPENPROJECT_WEB_MIN__THREADS: ${WEB_MIN_THREADS:-2}
      OPENPROJECT_WEB_MAX__THREADS: ${WEB_MAX_THREADS:-4}
      OPENPROJECT_RAILS__SERVE__STATIC__FILES: 'true'
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
      OPENPROJECT_HOST__NAME: ${OPENPROJECT_HOST__NAME:-nimble.engineer}
      OPENPROJECT_PROTOCOL: ${OPENPROJECT_PROTOCOL:-https}
      OPENPROJECT_HTTPS: ${OPENPROJECT_HTTPS:-true}
      OPENPROJECT_SEED_ADMIN_USER__PASSWORD: ${ADMIN_PASSWORD:-admin}
    volumes:
      - opdata:/var/openproject/assets
      - ./files:/var/openproject/files
      - ./enterprise_token_patch.rb:/app/app/models/enterprise_token.rb:ro
    networks:
      - network
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - cache

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.enterprise
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: postgresql://${DB_USER:-openproject}:${DB_PASSWORD:-openproject}@${DB_HOST:-192.168.3.78}:${DB_PORT:-5432}/${DB_NAME:-openproject}
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_RAILS__CACHE__STORE: memcache
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
    volumes:
      - opdata:/var/openproject/assets
      - ./files:/var/openproject/files
      - ./enterprise_token_patch.rb:/app/app/models/enterprise_token.rb:ro
    networks:
      - network
    command: bundle exec good_job start
    depends_on:
      - cache

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - network
